### ISSUE TITLE
script.js error

### ISSUE THREAD

**Issue by Andyauk** [MoneSuper/qbr-multicharacter#1]
was looking forward to trying this. but you cant make a toon, as when you submit you get this error

`Uncaught ReferenceError: profList is not defined (@qbr-multicharacter/html/script.js:204)`

    `const regTest = new RegExp(profList.join('|'), 'i');`

**Comment by MoneSuper** [comment]
> was looking forward to trying this. but you cant make a toon, as when you submit you get this error
> 
> `Uncaught ReferenceError: profList is not defined (@qbr-multicharacter/html/script.js:204)`
> 
> ```
> `const regTest = new RegExp(profList.join('|'), 'i');`
> ```

Thanks a lot I have added you on my readme for making this work!
